theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  plausible: beelearning.fr
  home:
    toc:
      disabled: false
  menu:
    primary:
      level_2:
        title:
          active: true
  breadcrumb:
    position: hero-end
  summary:
    position: hero
  search:
    active: false
  posts:
    index:
      layout: grid
  logo:
    header: /assets/images/logo.svg
    footer: /assets/images/logo-typo-verte.svg